"""Initial database schema

Revision ID: 4230559ae43f
Revises: 
Create Date: 2025-09-20 17:12:49.314050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4230559ae43f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_industries_id'), 'industries', ['id'], unique=False)
    op.create_table('pipeline_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_applications', sa.Integer(), nullable=True),
    sa.Column('applications_in_ai_processing', sa.Integer(), nullable=True),
    sa.Column('completed_evaluations', sa.Integer(), nullable=True),
    sa.Column('average_ai_score', sa.Float(), nullable=True),
    sa.Column('average_processing_time', sa.Float(), nullable=True),
    sa.Column('data_processing_conversion', sa.Float(), nullable=True),
    sa.Column('ai_analysis_conversion', sa.Float(), nullable=True),
    sa.Column('partner_review_conversion', sa.Float(), nullable=True),
    sa.Column('avg_days_data_processing', sa.Float(), nullable=True),
    sa.Column('avg_days_ai_analysis', sa.Float(), nullable=True),
    sa.Column('avg_days_manual_review', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_metrics_id'), 'pipeline_metrics', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'PARTNER', 'ANALYST', 'VIEWER', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('investment_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_size_weight', sa.Float(), nullable=True),
    sa.Column('team_experience_weight', sa.Float(), nullable=True),
    sa.Column('business_model_weight', sa.Float(), nullable=True),
    sa.Column('traction_weight', sa.Float(), nullable=True),
    sa.Column('financial_health_weight', sa.Float(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_weights_id'), 'investment_weights', ['id'], unique=False)
    op.create_table('startup_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('funding_stage', sa.Enum('PRE_SEED', 'SEED', 'SERIES_A', 'SERIES_B', 'SERIES_C', 'SERIES_D_PLUS', 'GROWTH', name='fundingstage'), nullable=True),
    sa.Column('funding_amount_requested', sa.Float(), nullable=True),
    sa.Column('current_arr', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('runway_months', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'DATA_PROCESSING', 'AI_ANALYSIS', 'MANUAL_REVIEW', 'PARTNER_REVIEW', 'COMPLETED', 'REJECTED', name='applicationstatus'), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('manual_score', sa.Float(), nullable=True),
    sa.Column('final_rating', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_analyst_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_notes', sa.Text(), nullable=True),
    sa.Column('bottleneck_stage', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_startup_analyst_status', 'startup_applications', ['assigned_analyst_id', 'status'], unique=False)
    op.create_index('idx_startup_industry_status', 'startup_applications', ['industry_id', 'status'], unique=False)
    op.create_index('idx_startup_status_created', 'startup_applications', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_startup_applications_company_name'), 'startup_applications', ['company_name'], unique=False)
    op.create_index(op.f('ix_startup_applications_id'), 'startup_applications', ['id'], unique=False)
    op.create_index(op.f('ix_startup_applications_status'), 'startup_applications', ['status'], unique=False)
    op.create_table('evaluation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_application_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.Enum('NEW', 'DATA_PROCESSING', 'AI_ANALYSIS', 'MANUAL_REVIEW', 'PARTNER_REVIEW', 'COMPLETED', 'REJECTED', name='applicationstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('NEW', 'DATA_PROCESSING', 'AI_ANALYSIS', 'MANUAL_REVIEW', 'PARTNER_REVIEW', 'COMPLETED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('time_in_previous_stage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['startup_application_id'], ['startup_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evaluation_startup_created', 'evaluation_history', ['startup_application_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_evaluation_history_id'), 'evaluation_history', ['id'], unique=False)
    op.create_table('financial_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_application_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('metric_unit', sa.String(length=50), nullable=True),
    sa.Column('metric_period', sa.String(length=100), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['startup_application_id'], ['startup_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_metrics_id'), 'financial_metrics', ['id'], unique=False)
    op.create_table('founders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_application_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('previous_companies', sa.Text(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('expertise_areas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['startup_application_id'], ['startup_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_founders_id'), 'founders', ['id'], unique=False)
    op.create_table('investment_memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_application_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('investment_highlights', sa.Text(), nullable=True),
    sa.Column('market_analysis', sa.Text(), nullable=True),
    sa.Column('business_model_analysis', sa.Text(), nullable=True),
    sa.Column('team_analysis', sa.Text(), nullable=True),
    sa.Column('financial_analysis', sa.Text(), nullable=True),
    sa.Column('risks_concerns', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=100), nullable=True),
    sa.Column('recommended_investment', sa.Float(), nullable=True),
    sa.Column('proposed_valuation', sa.Float(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('partner_review_scheduled', sa.Boolean(), nullable=True),
    sa.Column('partner_review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['startup_application_id'], ['startup_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_memos_id'), 'investment_memos', ['id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_application_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'PROCESSING', 'COMPLETED', 'FAILED', name='filestatus'), nullable=True),
    sa.Column('processing_progress', sa.Integer(), nullable=True),
    sa.Column('extraction_metadata', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['startup_application_id'], ['startup_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_startup_type', 'uploaded_files', ['startup_application_id', 'file_type'], unique=False)
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_index('idx_files_startup_type', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_investment_memos_id'), table_name='investment_memos')
    op.drop_table('investment_memos')
    op.drop_index(op.f('ix_founders_id'), table_name='founders')
    op.drop_table('founders')
    op.drop_index(op.f('ix_financial_metrics_id'), table_name='financial_metrics')
    op.drop_table('financial_metrics')
    op.drop_index(op.f('ix_evaluation_history_id'), table_name='evaluation_history')
    op.drop_index('idx_evaluation_startup_created', table_name='evaluation_history')
    op.drop_table('evaluation_history')
    op.drop_index(op.f('ix_startup_applications_status'), table_name='startup_applications')
    op.drop_index(op.f('ix_startup_applications_id'), table_name='startup_applications')
    op.drop_index(op.f('ix_startup_applications_company_name'), table_name='startup_applications')
    op.drop_index('idx_startup_status_created', table_name='startup_applications')
    op.drop_index('idx_startup_industry_status', table_name='startup_applications')
    op.drop_index('idx_startup_analyst_status', table_name='startup_applications')
    op.drop_table('startup_applications')
    op.drop_index(op.f('ix_investment_weights_id'), table_name='investment_weights')
    op.drop_table('investment_weights')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pipeline_metrics_id'), table_name='pipeline_metrics')
    op.drop_table('pipeline_metrics')
    op.drop_index(op.f('ix_industries_id'), table_name='industries')
    op.drop_table('industries')
    # ### end Alembic commands ###