"""Add authentication fields to users table

Revision ID: a40120993a6e
Revises: 4230559ae43f
Create Date: 2025-10-04 09:36:45.389335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a40120993a6e'
down_revision = '4230559ae43f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('stored_filename', sa.String(length=500), nullable=False))
    op.add_column('uploaded_files', sa.Column('content_type', sa.String(length=200), nullable=False))
    op.add_column('uploaded_files', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('uploaded_files', sa.Column('relative_path', sa.String(length=500), nullable=True))
    op.add_column('uploaded_files', sa.Column('storage_backend', sa.String(length=50), nullable=True))
    op.add_column('uploaded_files', sa.Column('is_processed', sa.Boolean(), nullable=True))
    op.add_column('uploaded_files', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('uploaded_files', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.add_column('uploaded_files', sa.Column('is_safe', sa.Boolean(), nullable=True))
    op.add_column('uploaded_files', sa.Column('upload_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('uploaded_files', sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('uploaded_files', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('uploaded_files', 'file_path',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('uploaded_files', 'mime_type')
    op.drop_column('uploaded_files', 'extraction_metadata')
    op.drop_column('uploaded_files', 'uploaded_at')
    op.drop_column('uploaded_files', 'filename')
    op.drop_column('uploaded_files', 'status')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'hashed_password')
    op.add_column('uploaded_files', sa.Column('status', sa.VARCHAR(length=10), nullable=True))
    op.add_column('uploaded_files', sa.Column('filename', sa.VARCHAR(length=500), nullable=False))
    op.add_column('uploaded_files', sa.Column('uploaded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('uploaded_files', sa.Column('extraction_metadata', sqlite.JSON(), nullable=True))
    op.add_column('uploaded_files', sa.Column('mime_type', sa.VARCHAR(length=200), nullable=True))
    op.alter_column('uploaded_files', 'file_path',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('uploaded_files', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('uploaded_files', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('uploaded_files', 'last_accessed_at')
    op.drop_column('uploaded_files', 'upload_timestamp')
    op.drop_column('uploaded_files', 'is_safe')
    op.drop_column('uploaded_files', 'metadata_json')
    op.drop_column('uploaded_files', 'description')
    op.drop_column('uploaded_files', 'is_processed')
    op.drop_column('uploaded_files', 'storage_backend')
    op.drop_column('uploaded_files', 'relative_path')
    op.drop_column('uploaded_files', 'file_hash')
    op.drop_column('uploaded_files', 'content_type')
    op.drop_column('uploaded_files', 'stored_filename')
    # ### end Alembic commands ###